### ISSUE TITLE
Please document how NAT traversal works

### ISSUE THREAD

**Issue by jgoerzen** [hackerschoice/gsocket#14]
Hi,

I just discovered this and it looks fantastic!  Could you please document how the TCP nat traversal works?  I was previously aware of UDP methods, but not TCP methods where both ends were behind NAT/firewall.  It would be fantastic to understand how it works.

thanks!

**Comment by SkyperTHC** [comment]
Both workstations establish an outgoing connection to the relay server. The relay server then forwards traffic between the two connected sockets. There are no incoming connections. Means that NAT does not need to be 'pierced'.

**Comment by jgoerzen** [comment]
Ah, I missed the relay server in the description.  My fault.  Sorry.
