### ISSUE TITLE
DSO files are distributed wrongly in bin dir used for executables

### ISSUE THREAD

**Issue by anthraxx** [hackerschoice/gsocket#32]
`gs_so` and `gs_uchroot_so` are not executables but in fact DSO libs. They should be distributed in the matching FHS directories like `/usr/lib` instead of putting them in the `bin` directory. 

This would be welcoming for distro folks :cat: 

Edit: I believe it would also make sense to move pure helper scripts as `gs_funcs` to the same place. Either the location can be probed or some of the scripts should be converted to `.in` files that autotools substitutes with configured `libdir` etc.

**Comment by rootTHC** [comment]
Can't use .in files for the shell script as this is a nightmare for development & testing (requires a ./configure before testing/development). So not happening that way.

Could probe in PREFIX/../lib etc but that gets tricky if the user specifies another libdir during ./configure. Risk of mismatching versions is huge. Easiest is to have everything in PREFIX/bin. Does packaging require this to be different (go with it until they complain and then see how this problem can be solved without hassle?)

**Comment by anthraxx** [comment]
Yes, distro packaging requires to only dist executables in the bin directories, such libs must be put somewhere else like `/usr/ib`.
I've seen code in the shell scripts that already probe for certain directories, can't that be used in a similar way? the probe can check for all valid FHS compliant directories, those include `/usr/local` etc?
If you think you don't want to solve this, I will need to provide downstream patches but I don't think that's a good approach and we try to cooperate as a distro policy with upstream instead of going nuts with downstream patches.

**Comment by xaitax** [comment]
You are right and I'll change it for the next build. Thanks old friend. :)

**Comment by xaitax** [comment]
I will change it for the next deb files old man.

**Comment by SkyperTHC** [comment]
> Yes, distro packaging requires to only dist executables in the bin directories, such libs must be put somewhere else like `/usr/ib`.

Where would include files for the bash scripts go? PREFIX/share/gsocket or PREFIX/lib?

Ok. I will put it in the next release. Are you packaging for ArchLinux?

**Comment by anthraxx** [comment]
> > Yes, distro packaging requires to only dist executables in the bin directories, such libs must be put somewhere else like `/usr/ib`.
> 
> Where would include files for the bash scripts go? PREFIX/share/gsocket or PREFIX/lib?
> 

I guess PREFIX/share/gsocket would work well :)

> Ok. I will put it in the next release. Are you packaging for ArchLinux?

Yes, was about to add gsocket to the repositories hence my earlier contributions as well. This is the last piece i would love to get solved before pushing :cat: 

Happy to test and review any changes :)

**Comment by rootTHC** [comment]
I've pushed this change to 'unstable' branch.  

1. dynamically loaded objects are now called `*.so` and installed to `${PREFIX}/lib/`. (and on cygwin .so.exe).
2. `gs_funcs` remains in `${PREFIX}/bin` but is now an executable that can be executed (it outputs the help). Otherwise there would be the need for a global configuration file (`/etc/gsocket.conf`) for the bash scripts (gs-sftp, gs-mount, blitz and gsocket) to determine the location of `gs_funcs`. That seems a bit overkill. Please advise. Comments? 

p.s. thanks for the packaging effort. Like to find out how you did it and what the process is.

```
./gs_funcs
Use gsocket, gs-netcat, gs-sftp, gs-mount or blitz instead.
```

Installed files:
```
./usr/local/bin/gs-sftp
./usr/local/bin/gs-mount
./usr/local/bin/blitz
./usr/local/bin/gs_funcs
./usr/local/bin/gsocket
./usr/local/bin/gs-netcat
./usr/local/lib/gs.so
./usr/local/lib/gs_uchroot.so
./usr/local/share/man/man1/gs-netcat.1
./usr/local/share/man/man1/gs-sftp.1
./usr/local/share/man/man1/blitz.1
./usr/local/share/man/man1/gsocket.1
./usr/local/share/man/man1/gs-mount.1
```

skyper

**Comment by rootTHC** [comment]
Also changed gs.so to gsocket_dso.so and gs_uchroot.so to gsocket_uchroot_dso.so.

```
./usr/bin/gs-sftp
./usr/bin/gs-mount
./usr/bin/blitz
./usr/bin/gsocket
./usr/bin/gs-netcat
./usr/etc/gsocket.conf
./usr/lib/gsocket_dso.so
./usr/lib/gsocket_uchroot_dso.so
./usr/share/man/man1/gs-netcat.1
./usr/share/man/man1/gs-sftp.1
./usr/share/man/man1/blitz.1
./usr/share/man/man1/gsocket.1
./usr/share/man/man1/gs-mount.1
./usr/share/gsocket/gs_funcs
```

**Comment by rootTHC** [comment]
`make distcheck` completes without errors now as well. Pushed to unstable. Will merge to master in a few days.
```
====================================================
gsocket-1.4.28-dev archives ready for distribution:
gsocket-1.4.28-dev.tar.gz
====================================================
```

**Comment by rootTHC** [comment]
This has now been release in 1.4.28 (and master branch).

**Comment by UnlimitedCookies** [comment]
> > Ok. I will put it in the next release. Are you packaging for ArchLinux?

> Yes, was about to add gsocket to the repositories hence my earlier contributions as well. This is the last piece i would love to get solved before pushing cat
@anthraxx Not trying to annoy, but what is the current status of an official arch package? I would be very interested in that. Currently, I am still using the `gsocket-git` package from the AUR.

**Comment by UnlimitedCookies** [comment]
@SkyperTHC Since your pings seem to have more impact than mine, perhaps you could nicely ask anthraxx again, whether he could be so prudent to add the `gsocket` package to the official arch repos. [Because I still cannot find it]

**Comment by anthraxx** [comment]
@UnlimitedCookies https://archlinux.org/packages/community/x86_64/gsocket/

**Comment by UnlimitedCookies** [comment]
> @UnlimitedCookies https://archlinux.org/packages/community/x86_64/gsocket/

Much appreciated -Thanks!
