### ISSUE TITLE
exec no such file (cosmetic)

### ISSUE THREAD

**Issue by c0decave** [hackerschoice/gsocket#33]
If no filename is given to gsocket it will still start and error out trying to execute:
```
$ gsocket 
Enter Secret (or press Enter to generate): 
=Secret         :"7F8hq1FxBKtQzEZgeKsyGo"
=Encryption     : SRP-AES-256-CBC-SHA-End2End (Prime: 4096 bits)
/usr/local/bin/gsocket: line 139: exec: : not found

```
Nothing bad, just cosmetic issue.

**Comment by rootTHC** [comment]
thanks. fixed in https://github.com/hackerschoice/gsocket/tree/unstable

(ps. try gsocket nc or gsocket ssh)
