### ISSUE TITLE
Provide binaries

### ISSUE THREAD

**Issue by amra** [hackerschoice/gsocket#56]
Provide binaries for instead of source code. It would be more straightforward to install in on a router. 

I tried to compile the code on Turris OS (OpenWrt fork). Many needed packages are not available in default repositories. So I installed Debian on LXC machine on the router and compiled it there. Then I copied it back to the router. 

Now the gsocket is missing a library `libnsl.so.1`, which seems to be part of RedHat distribution.

```
root@turris:~/software/gsocket# ./gsocket -s MySecret /usr/sbin/sshd -d
gsocket: =Encryption     : SRP-AES-256-CBC-SHA-End2End (Prime: 4096 bits)
Error loading shared library libnsl.so.1: No such file or directory (needed by /root/software/gsocket/gsocket_dso.so.0)
```

**Comment by SkyperTHC** [comment]
Already exists: [https://github.com/hackerschoice/binary/tree/main/gsocket/bin](https://github.com/hackerschoice/binary/tree/main/gsocket/bin)

There is also a OpenWRT Makefile: [https://github.com/hackerschoice/gsocket/tree/master/packaging/openwrt/gsocket](https://github.com/hackerschoice/gsocket/tree/master/packaging/openwrt/gsocket)

Let me know if this helps. Happy to help you and get this compiled for your platform. Join us on [https://t.me/thcorg](https://t.me/thcorg)
