### ISSUE TITLE
Can't run docker image on Odroid

### ISSUE THREAD

**Issue by chris24walsh** [hackerschoice/gsocket#57]
I'm trying to run gsocket on an odroid via the docker image, but I encounter this error:

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

Obviously the cpu architecture is wrong for the supplied image, can you advise if this can be supported?

**Comment by SkyperTHC** [comment]
Thanks for reporting this problem. I dont have Odroid. 

What command are you issuing to get this problem? Sounds like a docker problem and not a gsocket problem.

Try compile gsocket from source or use the binary from [here](https://github.com/hackerschoice/binary/tree/main/gsocket/bin).

Please reopen this issue if this does not solve your problem.
