### ISSUE TITLE
Setting a user supplied secret with X= does not work

### ISSUE THREAD

**Issue by snemes** [hackerschoice/gsocket#58]
Using the "X" environment variable does not seem to work and this snippet below will generate a new secret every time it is run:
```
# Pre-set a secret:
#   $ X=MySecret bash -c "$(curl -fsSL gsocket.io/x)"
```

1. The user supplied secret is saved here: https://github.com/hackerschoice/gsocket/blob/e4d734a3a4c1ac9fe8660e347b870e15c20fffe8/deploy/deploy.sh#L665

2. Then it gets overwritten in the `test_bin()` function, here: https://github.com/hackerschoice/gsocket/blob/e4d734a3a4c1ac9fe8660e347b870e15c20fffe8/deploy/deploy.sh#L574

**Comment by SkyperTHC** [comment]
Thanks for reporting. I can not re-produce this problem.
test_bin() is called _before_ line 665 (```GS_SECRET="$X"```) and the GS_SECRET variable is correctly set to the value of X.
<img width="608" alt="Screenshot 2021-11-15 at 06 58 01" src="https://user-images.githubusercontent.com/5938498/141736174-b8bfabe9-c213-4111-921b-deb954adcf39.png">

Please send me a screenshot

**Comment by snemes** [comment]
I tried to reproduce this again, but I could not. Looks like it might have been a failed uninstall of a previous gs-bd instance, and the X= variable is (obviously) disregarded when when trying to install on top of an existing installation.

Thanks for looking into this anyway. Closing issue.

**Comment by SkyperTHC** [comment]
Thanks for checking. While investigating this I found a bug in the description on the wepbpage instead.

```
X=ExampleSecretChangeMe && (command -v curl >/dev/null && bash -c "$(curl -fsSL gsocket.io/x)" || bash -c "$(wget -qO- gsocket.io/x)")
```
did not work but this one does (X is forwarded into the sub-shell)
```
X=ExampleSecretChangeMe && (command -v curl >/dev/null && X=$X bash -c "$(curl -fsSL gsocket.io/x)" || X=$X bash -c "$(wget -qO- gsocket.io/x)")
```
