### ISSUE TITLE
Can't connect to the server and replies Connection refused

### ISSUE THREAD

**Issue by gerryfrank10** [hackerschoice/gsocket#59]
There is a server i am connecting and i was connecting recently fine but suddenly there is no connection to the vps anymore.

_It replies Fri Nov 12 08:54:53 2021 [ID=1] Connection refused (no server listening) (2)_

and i used -w (for waiting and it also replies like )
_Connecting to 213.202.239.83:7350...
GSRN connection established [213.202.239.83:7350]._

but it doesn't connect back to me. 
Any help please

**Comment by SkyperTHC** [comment]
it means that there is no gs-netcat running on the server side or the running gs-netcat can not connect to the GSRN.

How did you install/start gs-netcat on the remote server?

Did the remote server reboot? can you still log in by other means? Check if gs-netcat is runnning (ps alxww | grep gs-netcat).
