### ISSUE TITLE
[Feature] Add bash, zsh, fish completions

### ISSUE THREAD

**Issue by UnlimitedCookies** [hackerschoice/gsocket#64]
see title

**Comment by SkyperTHC** [comment]
Please explain. It works fine for me. It depends if the remote host has bash/zsh/fish completion enabled and if it is enabled then it works just as it does via ssh.

Does that work for you?

**Comment by UnlimitedCookies** [comment]
I meant completion for gsocket itself (or to be specific for blitz, gs-mount, gs-netcat, gs-sftp and so on). 😁

**Comment by SkyperTHC** [comment]
i still dont understand. Can you explain on telegram? gs-netcat is a network protocol. I'm unsure of where you like to have 'completion'.

Alternative can you send a screenshot of what is not working or what behaviour you are currently getting compared to what you like to get?

The completion is normally provided by bash or by sftp. I feel I do not understand what you mean.
