### ISSUE TITLE
consider using $HOME/.cache or $HOME/.config

### ISSUE THREAD

**Issue by SkyperTHC** [hackerschoice/gsocket#70]
apparently $HOME/.usr is not 31337 enough.

**Comment by SkyperTHC** [comment]
$HOME/.config is preferable as $HOME/.cache might get cleaned...

**Comment by theaog** [comment]
$HOME/.config/dbus -- looks pretty innocuous at first glance, shouldn't spike any admin curiosity to investigate further into it.
