### ISSUE TITLE
github hosted binaries start failing on many networks

### ISSUE THREAD

**Issue by theaog** [hackerschoice/gsocket#71]
I noticed less and less hosts allow me to download binaries from github, I made an nginx server and copied the gs-binaries there:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/100999228/161319918-bbc4dc8d-081f-44d3-a354-5127657f61bf.png">

then updated the env vars `URL_BASE` and `URL_DEPLOY` to use my http server, and since then I haven't had an install failure.

I believe as time goes by this problem will be more and more frequent, thc should consider running their own download server as github gets blacklisted.

**Comment by SkyperTHC** [comment]
that's odd. What type of errors are you getting?

**Comment by SkyperTHC** [comment]
That can now be supplied with ```GS_BASE_URL=https://github.com/hackerschoice/binary/raw/main/gsocket/bin/``` or different URL.

Thank you for reporting this bug.
