### ISSUE TITLE
Binary as part of GitHub Release

### ISSUE THREAD

**Issue by amra** [hackerschoice/gsocket#81]
`hackerschoice/gsocket` releases should contain release binaries.

Currently, all releases miss binaries and contain only sources. Binaries are stored in a different [GitHub repository](https://github.com/hackerschoice/binary/tree/main/gsocket/bin). And it is inconvenient and confusing. 

GitHub provide release API: https://docs.github.com/en/rest/releases/releases#create-a-release

**Comment by SkyperTHC** [comment]
hmm. There is a reason for this: gsocket should be the source only. IT's a development repository. Binaries are not for developers but for users. So it makes sense to separate developers from users.

We do not bundle the binaries at all into a release tarball. Hmm. we could do it but what's the use case? Why not pull it from the binary rep instead and why duplicate the binaries to the source rep?

**Comment by amra** [comment]
I expressed myself badly. The idea is to take the binary file and upload it to a particular GitHub release as an asset. 

With a release I meant [GitHub Release feature](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases).

Then a single GitHub Release will contain:
- Release tarball containing only source code
- Binaries (as an Asset)
  - For multiple platforms
- Release notes
  - Including links to related GitHub issues
- Other metadata

### Comments

> There is a reason for this: gsocket should be the source only. IT's a development repository. Binaries are not for developers but for users. So it makes sense to separate developers from users.

The binary should not be part of a git repository, which should only contain only source code. 

> We do not bundle the binaries at all into a release tarball.

I agree on that too.

### Example - [Atom editor releases](https://github.com/atom/atom/releases)
![image](https://user-images.githubusercontent.com/174620/190008374-e4afe02d-87e2-4cda-9e5e-8e89045832b3.png)

**Comment by SkyperTHC** [comment]
this has now been done. thank you for your suggestions and explanations.
