### ISSUE TITLE
support mipsel-32

### ISSUE THREAD

**Issue by SkyperTHC** [hackerschoice/gsocket#90]
support MIPS Little Endian 32 bit (apparently some TV boxes use this)

Thanks @LouCipher for report.

**Comment by Lou-Cipher** [comment]
root@dm7020hd:~# uname -m ; uname -a ; cat /proc/cpuinfo
mips
Linux dm7020hd 3.2-dm7020hd #1 SMP Tue Aug 30 02:24:00 UTC 2022 mips mips mips GNU/Linux
system type		: BCM7413B1 STB platform
processor		: 0
cpu model		: Brcm4380 V4.4  FPU V0.1
BogoMIPS		: 403.45
cpu MHz			: 405.015
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: no
ASEs implemented	: mips16
shadow register sets	: 1
kscratch registers	: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

processor		: 1
cpu model		: Brcm4380 V4.4  FPU V0.1
BogoMIPS		: 403.45
cpu MHz			: 405.015
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: no
ASEs implemented	: mips16
shadow register sets	: 1
kscratch registers	: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

**Comment by muplagama** [comment]
root@vuduo2:~# uname -m ; uname -a ; cat /proc/cpuinfo
mips
Linux vuduo2 3.13.5 #1 SMP Fri Feb 26 14:36:47 CET 2021 mips GNU/Linux
system type             : BCM7425B2 STB platform
machine                 : Unknown
processor               : 0
cpu model               : Brcm4380 Broadcom BMIPS5000 V1.1  FPU V0.1
BogoMIPS                : 864.25
cpu MHz                 : 1305.097
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : yes
hardware watchpoint     : no
isa                     : mips1 mips2 mips32r1
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : Brcm4380 Broadcom BMIPS5000 V1.1  FPU V0.1
BogoMIPS                : 655.36
cpu MHz                 : 1305.097
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : yes
hardware watchpoint     : no
isa                     : mips1 mips2 mips32r1
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by SkyperTHC** [comment]
This has now been fixed MIPS32 Little Endian is working (the deploy script has been updated as well).

The static bins are at https://github.com/hackerschoice/binary/tree/main/gsocket/bin.
