### ISSUE TITLE
https://tiny.cc/gsinst 404 not found

### ISSUE THREAD

**Issue by donvend** [hackerschoice/gsocket#95]
Hi, 

The installer script can not be found on the tiny.cc.

 /bin/bash -c "$(curl -fsSL https://tiny.cc/gsinst)"
curl: (22) The requested URL returned error: 404

Could you please re-upload the script?

Thank you

**Comment by SkyperTHC** [comment]
Please use

```sh
bash -c "$(curl -fsSL gsocket.io/x)"
```

instead.

Where did you find the old reference to tiny.cc? tiny.cc's redirect expired after a while (dont know why) and I like to remove the old reference.

**Comment by donvend** [comment]
It was in the documentation on github: https://github.com/hackerschoice/gsocket/blob/master/deploy/README.md what you changed 6 min ago. :)
Ty, for the info.

**Comment by SkyperTHC** [comment]
Ok. thanks for getting back to me. I fixed (hopefully) the last reference to tiny-cc :>
